// @ts-check
const { createConfigTester } = require("../createConfigTester.js")

const test = createConfigTester()

test("globals", () => ({
  valid: [
    "Dusk.initLogic()",
    "Math.abs()",
    "Math.round()",
    "Math.cos()",
    "Math.sin()",
    "Math.pow()",
    "Math.log()",
    "Math.random()",
    "123 * Math.PI",
    "const matematik = {}; Object.assign(matematik, { hest: 'snel' })",
    "isNaN(12)",
    "isFinite(12)",
    "Number.isNaN(12)",
    "if (42 < Infinity) { }",
    "if (typeof Dusk === 'undefined') { }",
    "parseFloat('1.123')",
    "globalThis.Math.pow()",
    "new Set()",
    "console.log(123)",
  ],
  invalid: [
    ["Pdusk.initLogic()", "no-undef"],
    ["Object.assign(window, { hest: 'snel' })", "no-restricted-globals"],
    ['require("hest")', "no-undef"],
    ["window.Math.pow()", "no-restricted-globals"],
    ["global.Math.pow()", "no-restricted-globals"],
    ["Performance.now()", "no-restricted-globals"],
    ["performance.now()", "no-restricted-globals"],
    ["global.hest = 'snel'", "dusk/no-global-scope-mutation"],
    ["globalThis.hest = 'snel'", "dusk/no-global-scope-mutation"],
    ["globalThis.Math.cos = () => {};", "dusk/no-global-scope-mutation"],
    ["new XMLHttpRequest()", "no-restricted-globals"],
    ["fetch('https://dusk.ai')", "no-restricted-globals"],
    ["setTimeout(() => {})", "no-restricted-globals"],
    ["clearTimeout()", "no-restricted-globals"],
    ["setInterval()", "no-restricted-globals"],
    ["clearInterval()", "no-restricted-globals"],
    ["alert()", "no-restricted-globals"],
    ["Dusk.init()", "no-restricted-properties"],
    ["Dusk.initClient()", "no-restricted-properties"],
    ["Dusk.deterministicRandom(1)", "no-restricted-properties"],
    ['eval("hest")', "no-restricted-globals"],
    ["new Date()", "no-restricted-globals"],
    ["const date = Date; date.now()", "no-restricted-globals"],
    ["Date.now()", "no-restricted-globals"],
    ["new Intl.NumberFormat()", "no-restricted-globals"],
    ["new Symbol()", "no-restricted-globals"],
    ["parseFloat = function() {}", "no-global-assign"],
    ['Math.floor(3).toLocaleString("en-US")', "no-restricted-properties"],
    ["'abc'.toLocaleLowerCase()", "no-restricted-properties"],
    ["'abc'.toLocaleUpperCase()", "no-restricted-properties"],
    ["'abc'.localeCompare()", "no-restricted-properties"],
    ["x.then(y)", "no-restricted-properties"],
  ],
}))
