export const sectionLineWidth = 2
export const shadowBlur = 10
export const deadCircleRadius = 11
export const avatarRadius = 10
export const avatarBorder = 1
export const optimisticSectionIterations = 15
export const deathRevealDelayMs = 100
export const endOfRoundRevealDelayMs = deathRevealDelayMs + 1000
export const defaultTransitionMs = 400
