export const countdownDurationSeconds = 5
export const endOfRoundDurationSeconds = 3
export const maxScoreBeforeGameOver = 10
export const boardSize = { width: 600, height: 900 }
export const movePixelsPerTick = 3
export const turnDegreesPerTick = 3
export const gapChancePerTick = 0.01
export const placeGapForTicks = 20
export const minTicksToNextGap = 30
export const colors = ["#BCFE00", "#10D4FF", "#FF32D2", "#FF9C27"]
